In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

os.environ["OPENCV_IO_MAX_IMAGE_PIXELS"] = pow(2,40).__str__()
import cv2

import torch

DATA_PATH = "E:/ML/UBC"
print(DATA_PATH)

E:/ML/UBC

In [2]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using cuda device

## Dataset

In [3]:
testList = pd.read_csv(os.path.join(DATA_PATH, "test.csv"))
testList.head()

   image_id  image_width  image_height
0        41        28469         16987

In [5]:
from sklearn.preprocessing import LabelEncoder
import warnings
import pickle 

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    with open(os.path.join("./", 'LabelEncoder5.pkl'), 'rb') as f:
        enc = pickle.load(f) 
    print(enc.classes_)
    print(enc.transform(["LGSC"]))

['CC' 'EC' 'HGSC' 'LGSC' 'MC']
[3]

In [16]:
IMG_SIZE = (384, 384)
eps=1e-12

In [15]:
PatchSize=512

#Testing Flag
DEV=True

if DEV:
    allIds = [41, 99, 13568,17637,12442]
else:
    allIds = testList["image_id"].unique()

def getPatches(data):
    patches=[]
#     if data.shape[0]<5000 and data.shape[1]<5000:
#         #probably TMA
#         PatchSize=1024
#     else:
#         #WSI
#         PatchSize=512
    NRows = data.shape[0]//PatchSize
    NCols = data.shape[1]//PatchSize
    div = np.max([(NRows*NCols)//1500, 1]).astype(np.int64)
#     print(f"{div=}")
    
    for j in range(NRows):
        yPos = PatchSize*j
        for i in range(NCols):
            # Only take every n-th patch due to memory restrictions
            if (j*NCols + i)%div == 0:
                xPos = PatchSize*i
                patch = data[yPos:yPos+PatchSize, xPos:xPos+PatchSize]
                hist , _ = np.histogram(patch, bins=10, range=(0.0,255.0))
                # If most pixels are very bright or dark the patch is outside the relevant area
                if ((np.sum(hist[2:-2]))/(np.sum(hist)+eps)) < 0.1 or (hist[0])/np.sum(hist)>0.3:
                    continue
                w, h = patch.shape[1], patch.shape[0]
                if not (w == IMG_SIZE[0] and h == IMG_SIZE[1]):
                    patch = cv2.resize(patch, IMG_SIZE)
                patches.append(patch)
#     patches=[]
    return np.array(patches).astype(np.float32)/255.0


def getData(id):
    if DEV:
        imFile =  os.path.join(DATA_PATH, "train_images_test", str(id)+".png")
    else:
        imFile =  os.path.join(DATA_PATH, "test_images", str(id)+".png")
    if os.path.exists(imFile):
#         data = cv2.imread(imFile)[:,:,::-1]
        data = cv2.imread(imFile)
        data = cv2.cvtColor(data, cv2.COLOR_BGR2RGB ) 
        patches = getPatches(data)
        del data
        return patches, id
    else:
        return np.array([]).astype(np.float32), id


def generator():
    for trainId in allIds:
        yield getData(trainId)

In [12]:
X, fid = getData(99)

In [7]:
# g = generator()
# testInstance = next(g)
# testInstance[0].shape

In [8]:
# # plt.imshow(testInstance[0][0,:,:,:])
# print("id ", testInstance[1])
# print("max ", np.max(testInstance[0]))
# print("len ", len(testInstance[0]))
# print("shape ", testInstance[0].shape)


# plt.figure(figsize=(12,12))
# for i in range(49):
#     plt.subplot(7,7,i+1)
#     plt.imshow(testInstance[0][i,:,:,:])
#     _= plt.axis("off")

In [9]:
# del testInstance, g

## Stage 1: Detection

In [23]:
from torch import nn
import torch
import timm


classifier = timm.create_model('resnet34d', pretrained=False, num_classes=len(enc.classes_))

checkpoint = torch.load(os.path.join("./", "seg_resnet34d_384_5_epoch_15_ValAcc_0.9726.pt"))
print(classifier.load_state_dict(checkpoint['model_state_dict']))

del checkpoint

detector = timm.create_model('resnet18', pretrained=False, num_classes=1)

checkpoint2 = torch.load(os.path.join("./", "B_resnet18_384_epoch_10_ValAcc_0.9635.pt"))
print(detector.load_state_dict(checkpoint2['model_state_dict']))

del checkpoint2

<All keys matched successfully>
<All keys matched successfully>

In [46]:
from torchvision.transforms import v2


detections={}
result=[]
threshold = 0.5

transforms = v2.Compose([
    v2.ToDtype(torch.float32),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

print("Start Test...")

detector = detector.to(device)
detector.eval()

classifier = classifier.to(device)
classifier.eval()

for batch, fid in enumerate(allIds):
    X, _ = getData(fid)
    X = torch.Tensor(X)
    if X.shape[0] == 0:
        result.append([fid, "HGSC"])
    elif not X.shape[1] == IMG_SIZE[0] or not X.shape[2] == IMG_SIZE[1] or not X.shape[3]==3:
        result.append([fid, "HGSC"])
    else:
        X = X.movedim(-1,1)
    
        #Detection
        X = transforms(X)
        print(batch, fid, X.shape)
        detectionsTemp=[]
        totalNum = X.shape[0]
        if totalNum>20:
            splits = np.linspace(0,totalNum, totalNum//10, dtype=np.int32)
            for j,spl in enumerate(splits):
                if j==splits.shape[0]-1:
                    break
                splittedX = X[spl: splits[j+1],:]
                splittedX = splittedX.to(device)
                preds = detector(splittedX)
                preds = torch.nn.functional.sigmoid(preds)
                preds = torch.flatten(preds) > threshold
                detectionsTemp = [*detectionsTemp, *preds.detach().cpu().numpy()]
                del splittedX, preds
        else:
            X = X.to(device)
            preds = detector(X)
            preds = torch.nn.functional.sigmoid(preds)
            preds = torch.flatten(preds) > threshold
            detectionsTemp = [ *preds.detach().cpu().numpy()]
            del preds
            
        detectionsTemp = np.array(detectionsTemp)
#         detections[fid] = detectionsTemp
        
        cancerousPatches = X[detectionsTemp]
        
        del X
        
        print(cancerousPatches.shape)
        
        #Prediction
        predictions=[]
        totalNum = cancerousPatches.shape[0]
        if totalNum == 0:
            result.append([fid, "HGSC"])
            continue
        elif totalNum>20:
            splits = np.linspace(0,totalNum, totalNum//10, dtype=np.int32)
            for j,spl in enumerate(splits):
                if j==splits.shape[0]-1:
                    break
                splittedX = cancerousPatches[spl: splits[j+1],:]
                splittedX = splittedX.to(device)

                preds = classifier(splittedX)
                preds = torch.nn.functional.softmax(preds, dim=1)
                predictions = [*predictions, *preds.detach().cpu().numpy()]
                del splittedX, preds
        else:
            cancerousPatches = cancerousPatches.to(device)
            preds = classifier(cancerousPatches)
            preds = torch.nn.functional.softmax(preds, dim=1)
            predictions = [ *preds.detach().cpu().numpy()]
            del preds
            
        pred = np.mean(predictions, axis=0)
#         pred = np.max(predictions, axis=0)

#         print(pred)
        targetLabel = np.argmax(pred)
        prob = pred[targetLabel]

        label = enc.inverse_transform([targetLabel])[0]
        result.append([fid, label])
        del cancerousPatches
        torch.cuda.empty_cache()

Start Test...

  0%|          | 0/100 [00:00<?, ?it/s]

0 41 torch.Size([1, 3, 384, 384])

  3%|▎         | 3/100 [00:00<00:12,  7.83it/s]

torch.Size([0, 3, 384, 384])
1 99 torch.Size([1, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([1, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([1, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([1, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([2, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([2, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([2, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([2, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([2, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([3, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([3, 3, 384, 384])

  4%|▍         | 4/100 [00:00<00:13,  7.08it/s]

torch.Size([0, 3, 384, 384])
2 13568 torch.Size([3, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([3, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([3, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([4, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([4, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([4, 3, 384, 384])

  5%|▌         | 5/100 [00:00<00:14,  6.43it/s]

torch.Size([0, 3, 384, 384])
3 17637 torch.Size([4, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([4, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([5, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([5, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([5, 3, 384, 384])

  6%|▌         | 6/100 [00:00<00:17,  5.52it/s]

torch.Size([0, 3, 384, 384])
3 17637 torch.Size([5, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([5, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([6, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([6, 3, 384, 384])
torch.Size([0, 3, 384, 384])

  7%|▋         | 7/100 [00:01<00:19,  4.72it/s]

2 13568 torch.Size([6, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([6, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([6, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([7, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([7, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([7, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([7, 3, 384, 384])

  8%|▊         | 8/100 [00:01<00:23,  3.99it/s]

torch.Size([0, 3, 384, 384])
4 12442 torch.Size([7, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([8, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([8, 3, 384, 384])

  9%|▉         | 9/100 [00:01<00:25,  3.62it/s]

torch.Size([0, 3, 384, 384])
2 13568 torch.Size([8, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([8, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([8, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([9, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([9, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([9, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 10%|█         | 10/100 [00:02<00:27,  3.22it/s]

3 17637 torch.Size([9, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([9, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([10, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([10, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([10, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 11%|█         | 11/100 [00:02<00:30,  2.89it/s]

3 17637 torch.Size([10, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([10, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([11, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([11, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([11, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 12%|█▏        | 12/100 [00:03<00:33,  2.59it/s]

3 17637 torch.Size([11, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([11, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([12, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([12, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([12, 3, 384, 384])

 13%|█▎        | 13/100 [00:03<00:36,  2.36it/s]

torch.Size([0, 3, 384, 384])
3 17637 torch.Size([12, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([12, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([13, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([13, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([13, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([13, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 14%|█▍        | 14/100 [00:04<00:39,  2.17it/s]

4 12442 torch.Size([13, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([14, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([14, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([14, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([14, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([14, 3, 384, 384])

 15%|█▌        | 15/100 [00:04<00:43,  1.97it/s]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([15, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([15, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([15, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([15, 3, 384, 384])

 16%|█▌        | 16/100 [00:05<00:46,  1.80it/s]

torch.Size([0, 3, 384, 384])
4 12442 torch.Size([15, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([16, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([16, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([16, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([16, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([16, 3, 384, 384])

 17%|█▋        | 17/100 [00:06<00:49,  1.68it/s]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([17, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([17, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([17, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([17, 3, 384, 384])

 18%|█▊        | 18/100 [00:06<00:52,  1.57it/s]

torch.Size([0, 3, 384, 384])
4 12442 torch.Size([17, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([18, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([18, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([18, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([18, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([18, 3, 384, 384])

 19%|█▉        | 19/100 [00:07<00:54,  1.50it/s]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([19, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([19, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([19, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([19, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 20%|██        | 20/100 [00:08<00:56,  1.42it/s]

4 12442 torch.Size([19, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([20, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([20, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([20, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([20, 3, 384, 384])

 21%|██        | 21/100 [00:09<00:58,  1.36it/s]

torch.Size([0, 3, 384, 384])
4 12442 torch.Size([20, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([21, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([21, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([21, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([21, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([21, 3, 384, 384])

 22%|██▏       | 22/100 [00:10<01:00,  1.29it/s]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([22, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([22, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([22, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([22, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 23%|██▎       | 23/100 [00:11<01:03,  1.22it/s]

4 12442 torch.Size([22, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([23, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([23, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([23, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([23, 3, 384, 384])

 24%|██▍       | 24/100 [00:12<01:07,  1.12it/s]

torch.Size([0, 3, 384, 384])
4 12442 torch.Size([23, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([24, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([24, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([24, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([24, 3, 384, 384])
torch.Size([0, 3, 384, 384])

 25%|██▌       | 25/100 [00:14<01:32,  1.24s/it]

4 12442 torch.Size([24, 3, 384, 384])
torch.Size([0, 3, 384, 384])
0 41 torch.Size([25, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([25, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([25, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([25, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([25, 3, 384, 384])

 26%|██▌       | 26/100 [00:16<01:51,  1.50s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([26, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([26, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([26, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([26, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([26, 3, 384, 384])

 27%|██▋       | 27/100 [00:18<02:11,  1.81s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([27, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([27, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([27, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([27, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([27, 3, 384, 384])

 28%|██▊       | 28/100 [00:21<02:23,  1.99s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([28, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([28, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([28, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([28, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([28, 3, 384, 384])

 29%|██▉       | 29/100 [00:23<02:31,  2.14s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([29, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([29, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([29, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([29, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([29, 3, 384, 384])

 30%|███       | 30/100 [00:26<02:35,  2.22s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([30, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([30, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([30, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([30, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([30, 3, 384, 384])

 31%|███       | 31/100 [00:27<02:17,  1.99s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([31, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([31, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([31, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([31, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([31, 3, 384, 384])

 32%|███▏      | 32/100 [00:28<02:03,  1.81s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([32, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([32, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([32, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([32, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([32, 3, 384, 384])

 33%|███▎      | 33/100 [00:30<01:53,  1.70s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([33, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([33, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([33, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([33, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([33, 3, 384, 384])

 34%|███▍      | 34/100 [00:31<01:46,  1.61s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([34, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([34, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([34, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([34, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([34, 3, 384, 384])

 35%|███▌      | 35/100 [00:33<01:41,  1.57s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([35, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([35, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([35, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([35, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([35, 3, 384, 384])

 36%|███▌      | 36/100 [00:34<01:40,  1.57s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([36, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([36, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([36, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([36, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([36, 3, 384, 384])

 37%|███▋      | 37/100 [00:36<01:39,  1.58s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([37, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([37, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([37, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([37, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([37, 3, 384, 384])

 38%|███▊      | 38/100 [00:38<01:38,  1.58s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([38, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([38, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([38, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([38, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([38, 3, 384, 384])

 39%|███▉      | 39/100 [00:39<01:37,  1.59s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([39, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([39, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([39, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([39, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([39, 3, 384, 384])

 40%|████      | 40/100 [00:41<01:37,  1.62s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([40, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([40, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([40, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([40, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([40, 3, 384, 384])

 41%|████      | 41/100 [00:43<01:39,  1.69s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([41, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([41, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([41, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([41, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([41, 3, 384, 384])

 42%|████▏     | 42/100 [00:45<01:41,  1.76s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([42, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([42, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([42, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([42, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([42, 3, 384, 384])

 43%|████▎     | 43/100 [00:47<01:43,  1.82s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([43, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([43, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([43, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([43, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([43, 3, 384, 384])

 44%|████▍     | 44/100 [00:49<01:45,  1.89s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([44, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([44, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([44, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([44, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([44, 3, 384, 384])

 45%|████▌     | 45/100 [00:51<01:46,  1.94s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([45, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([45, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([45, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([45, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([45, 3, 384, 384])

 46%|████▌     | 46/100 [00:53<01:45,  1.95s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([46, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([46, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([46, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([46, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([46, 3, 384, 384])

 47%|████▋     | 47/100 [00:55<01:42,  1.94s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([47, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([47, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([47, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([47, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([47, 3, 384, 384])

 48%|████▊     | 48/100 [00:57<01:41,  1.95s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([48, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([48, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([48, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([48, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([48, 3, 384, 384])

 49%|████▉     | 49/100 [00:59<01:40,  1.98s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([49, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([49, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([49, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([49, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([49, 3, 384, 384])

 50%|█████     | 50/100 [01:01<01:40,  2.01s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([50, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([50, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([50, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([50, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([50, 3, 384, 384])

 51%|█████     | 51/100 [01:03<01:40,  2.05s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([51, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([51, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([51, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([51, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([51, 3, 384, 384])

 52%|█████▏    | 52/100 [01:05<01:40,  2.09s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([52, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([52, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([52, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([52, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([52, 3, 384, 384])

 53%|█████▎    | 53/100 [01:07<01:39,  2.13s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([53, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([53, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([53, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([53, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([53, 3, 384, 384])

 54%|█████▍    | 54/100 [01:10<01:40,  2.18s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([54, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([54, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([54, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([54, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([54, 3, 384, 384])

 55%|█████▌    | 55/100 [01:12<01:40,  2.24s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([55, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([55, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([55, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([55, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([55, 3, 384, 384])

 56%|█████▌    | 56/100 [01:14<01:41,  2.30s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([56, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([56, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([56, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([56, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([56, 3, 384, 384])

 57%|█████▋    | 57/100 [01:17<01:41,  2.36s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([57, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([57, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([57, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([57, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([57, 3, 384, 384])

 58%|█████▊    | 58/100 [01:19<01:41,  2.41s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([58, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([58, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([58, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([58, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([58, 3, 384, 384])

 59%|█████▉    | 59/100 [01:22<01:40,  2.45s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([59, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([59, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([59, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([59, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([59, 3, 384, 384])

 60%|██████    | 60/100 [01:24<01:38,  2.46s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([60, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([60, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([60, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([60, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([60, 3, 384, 384])

 61%|██████    | 61/100 [01:27<01:36,  2.47s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([61, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([61, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([61, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([61, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([61, 3, 384, 384])

 62%|██████▏   | 62/100 [01:29<01:34,  2.48s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([62, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([62, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([62, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([62, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([62, 3, 384, 384])

 63%|██████▎   | 63/100 [01:32<01:32,  2.51s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([63, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([63, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([63, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([63, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([63, 3, 384, 384])

 64%|██████▍   | 64/100 [01:35<01:31,  2.54s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([64, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([64, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([64, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([64, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([64, 3, 384, 384])

 65%|██████▌   | 65/100 [01:37<01:30,  2.59s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([65, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([65, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([65, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([65, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([65, 3, 384, 384])

 66%|██████▌   | 66/100 [01:40<01:29,  2.64s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([66, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([66, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([66, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([66, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([66, 3, 384, 384])

 67%|██████▋   | 67/100 [01:43<01:29,  2.72s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([67, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([67, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([67, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([67, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([67, 3, 384, 384])

 68%|██████▊   | 68/100 [01:46<01:31,  2.87s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([68, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([68, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([68, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([68, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([68, 3, 384, 384])

 69%|██████▉   | 69/100 [01:49<01:30,  2.91s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([69, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([69, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([69, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([69, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([69, 3, 384, 384])

 70%|███████   | 70/100 [01:53<01:31,  3.04s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([70, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([70, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([70, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([70, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([70, 3, 384, 384])

 71%|███████   | 71/100 [01:56<01:29,  3.08s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([71, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([71, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([71, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([71, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([71, 3, 384, 384])

 72%|███████▏  | 72/100 [01:59<01:24,  3.03s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([72, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([72, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([72, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([72, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([72, 3, 384, 384])

 73%|███████▎  | 73/100 [02:01<01:20,  2.99s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([73, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([73, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([73, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([73, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([73, 3, 384, 384])

 74%|███████▍  | 74/100 [02:04<01:16,  2.95s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([74, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([74, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([74, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([74, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([74, 3, 384, 384])

 75%|███████▌  | 75/100 [02:07<01:14,  2.97s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([75, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([75, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([75, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([75, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([75, 3, 384, 384])

 76%|███████▌  | 76/100 [02:11<01:12,  3.02s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([76, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([76, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([76, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([76, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([76, 3, 384, 384])

 77%|███████▋  | 77/100 [02:14<01:11,  3.09s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([77, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([77, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([77, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([77, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([77, 3, 384, 384])

 78%|███████▊  | 78/100 [02:17<01:09,  3.16s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([78, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([78, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([78, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([78, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([78, 3, 384, 384])

 79%|███████▉  | 79/100 [02:20<01:06,  3.19s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([79, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([79, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([79, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([79, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([79, 3, 384, 384])

 80%|████████  | 80/100 [02:24<01:04,  3.24s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([80, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([80, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([80, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([80, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([80, 3, 384, 384])

 81%|████████  | 81/100 [02:27<01:02,  3.27s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([81, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([81, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([81, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([81, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([81, 3, 384, 384])

 82%|████████▏ | 82/100 [02:30<00:58,  3.24s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([82, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([82, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([82, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([82, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([82, 3, 384, 384])

 83%|████████▎ | 83/100 [02:34<00:55,  3.28s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([83, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([83, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([83, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([83, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([83, 3, 384, 384])

 84%|████████▍ | 84/100 [02:37<00:52,  3.29s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([84, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([84, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([84, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([84, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([84, 3, 384, 384])

 85%|████████▌ | 85/100 [02:40<00:49,  3.29s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([85, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([85, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([85, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([85, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([85, 3, 384, 384])

 86%|████████▌ | 86/100 [02:44<00:46,  3.33s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([86, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([86, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([86, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([86, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([86, 3, 384, 384])

 87%|████████▋ | 87/100 [02:47<00:44,  3.39s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([87, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([87, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([87, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([87, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([87, 3, 384, 384])

 88%|████████▊ | 88/100 [02:51<00:40,  3.40s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([88, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([88, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([88, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([88, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([88, 3, 384, 384])

 89%|████████▉ | 89/100 [02:56<00:42,  3.88s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([89, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([89, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([89, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([89, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([89, 3, 384, 384])

 90%|█████████ | 90/100 [03:00<00:40,  4.06s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([90, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([90, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([90, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([90, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([90, 3, 384, 384])

 91%|█████████ | 91/100 [03:04<00:35,  3.99s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([91, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([91, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([91, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([91, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([91, 3, 384, 384])

 92%|█████████▏| 92/100 [03:08<00:31,  3.99s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([92, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([92, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([92, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([92, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([92, 3, 384, 384])

 93%|█████████▎| 93/100 [03:12<00:28,  4.05s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([93, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([93, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([93, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([93, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([93, 3, 384, 384])

 94%|█████████▍| 94/100 [03:16<00:24,  4.07s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([94, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([94, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([94, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([94, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([94, 3, 384, 384])

 95%|█████████▌| 95/100 [03:20<00:20,  4.07s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([95, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([95, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([95, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([95, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([95, 3, 384, 384])

 96%|█████████▌| 96/100 [03:24<00:16,  4.10s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([96, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([96, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([96, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([96, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([96, 3, 384, 384])

 97%|█████████▋| 97/100 [03:29<00:12,  4.11s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([97, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([97, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([97, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([97, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([97, 3, 384, 384])

 98%|█████████▊| 98/100 [03:33<00:08,  4.17s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([98, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([98, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([98, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([98, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([98, 3, 384, 384])

 99%|█████████▉| 99/100 [03:37<00:04,  4.20s/it]

torch.Size([0, 3, 384, 384])
0 41 torch.Size([99, 3, 384, 384])
torch.Size([0, 3, 384, 384])
1 99 torch.Size([99, 3, 384, 384])
torch.Size([0, 3, 384, 384])
2 13568 torch.Size([99, 3, 384, 384])
torch.Size([0, 3, 384, 384])
3 17637 torch.Size([99, 3, 384, 384])
torch.Size([0, 3, 384, 384])
4 12442 torch.Size([99, 3, 384, 384])

100%|██████████| 100/100 [03:42<00:00,  2.22s/it]

torch.Size([0, 3, 384, 384])

In [38]:
detectionsTemp

array([False])

## Stage 2: Classification

In [12]:

# classifier = timm.create_model('resnet34d', pretrained=False, num_classes=len(enc.classes_))

# checkpoint = torch.load(os.path.join("/kaggle/input/ubc-model/", "seg_resnet34d_384_5_epoch_15_ValAcc_0.9726.pt"))
# print(classifier.load_state_dict(checkpoint['model_state_dict']))

# del checkpoint

In [13]:
# from torchvision.transforms import v2

# result=[]

# threshold = 0.5

# transforms = v2.Compose([
#     v2.ToDtype(torch.float32),
#     v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
# ])

# print("Start Test...")


# classifier = classifier.to(device)
# classifier.eval()

# for batch, fid in enumerate(allIds):
#     X, _ = getData(fid)
#     X = torch.Tensor(X)
#     if X.shape[0] == 0:
#         result.append([fid, "Other"])
#     elif not X.shape[1] == IMG_SIZE[0] or not X.shape[2] == IMG_SIZE[1] or not X.shape[3]==3:
#         result.append([fid, "HGSC"])
#     else:
#         X = X.movedim(-1,1)
            
#         detectionsTemp = detections[fid]
#         cancerousPatches = X[detectionsTemp]
        
#         del X
        
#         print(cancerousPatches.shape)
        
#         #Prediction
#         predictions=[]
#         totalNum = cancerousPatches.shape[0]
#         if totalNum == 0:
#             result.append([fid, "Other"])
#         elif totalNum>10:
#             splits = np.linspace(0,totalNum, totalNum//10, dtype=np.int32)
#             for j,spl in enumerate(splits):
#                 if j==splits.shape[0]-1:
#                     break
#                 splittedX = cancerousPatches[spl: splits[j+1],:]
#                 splittedX = splittedX.to(device)

#                 preds = classifier(splittedX)
#                 preds = torch.nn.functional.softmax(preds, dim=1)
#                 predictions = [*predictions, *preds.detach().cpu().numpy()]
#                 del splittedX, preds
#         else:
#             cancerousPatches = cancerousPatches.to(device)
#             preds = classifier(cancerousPatches)
#             preds = torch.nn.functional.softmax(preds, dim=1)
#             predictions = [ *preds.detach().cpu().numpy()]
#             del preds
            
#         pred = np.mean(predictions, axis=0)
# #         pred = np.max(predictions, axis=0)

# #         print(pred)
#         targetLabel = np.argmax(pred)
#         prob = pred[targetLabel]

#         label = enc.inverse_transform([targetLabel])[0]
#         result.append([fid, label])
#         del cancerousPatches

In [35]:
df = pd.DataFrame(result, columns=['image_id', "label"])
df.head()

   image_id label
0        41  HGSC
1        99  HGSC
2     13568  HGSC
3     17637  HGSC
4     12442  HGSC

In [27]:
# df.to_csv("./submission.csv", index=False)